### ISSUE TITLE
Tooltip keybind not working with shift

### ISSUE THREAD

**Issue by Glisch** [climbridecode/herblore-recipes#14]
When setting the tooltip to shift, it does not trigger the tooltip to appear. I have tried turning the plugin on and off, uninstalling and reinstalling, closing and reopening runelite, reinstalling runelite. Also does not work via either left or right shift. The keybind tooltip does work when I set it to characters other than shift (tried several random keys) or when I set it to be always on (no keybind used). I can verify that the shift key on the keyboard does work in general.

This worked up until a few days ago. I've tried going through plugins to see if another might be interfering with it, but didn't find anything.

**Comment by climbridecode** [comment]
Thanks for opening the issue. I'll take a look today and hopefully get a fix out!

**Comment by climbridecode** [comment]
The issue for this is RuneLite doesn't consider Alt and Shift keys as "action" keys, as they're reserved for game-level or lower client-level features such as shift to drop and Alt to move overlays around.

**Comment by Glisch** [comment]
> The issue for this is RuneLite doesn't consider Alt and Shift keys as "action" keys, as they're reserved for game-level or lower client-level features such as shift to drop and Alt to move overlays around.

Just for clarity, I guess this is a recent change? Using shift worked (since I first installed this plugin I dont even know how long ago). It just stopped working in the past week or so (don't know the exact time, but very recent).

I will update to a different keybind, just unfortunate

EDIT: Also, thanks for your work on the plugin. It's much appreciated

**Comment by climbridecode** [comment]
No worries, and I did recently do a refactor that must've caused this issue. I'm gonna look at what I did differently in the past hehe

**Comment by climbridecode** [comment]
Though I did merge the refactor in two weeks ago now. I don't see any major differences in how I did it previously vs how it's being done now.. But I'll continue investigating. I wonder if there was a change in how RuneLite treats a "Shift" and "Alt" keybind because the function from the Config `interface` that returns the bound key is always returning the default `Keybind.NOT_SET` when `Shift` is the keybind ([code](https://github.com/climbridecode/herblore-recipes/blob/main/src/main/java/com/herblorerecipes/HerbloreRecipesConfig.java#L260)), but when other keys are set (like `A` or `B`) it returns a proper keyCode.

**Comment by climbridecode** [comment]
Good news! I fixed the issue. Going to commit a fix into this repo and open a PR in the plugin-hub :). It was indeed a bug I introduced in my refactor.

If you're interested: https://github.com/climbridecode/herblore-recipes/commit/3138534bf7d1b9418965f406cc4841907a76a140

PR: https://github.com/runelite/plugin-hub/pull/4467

**Comment by Glisch** [comment]
Awesome, thanks so much for the work on this!
