### ISSUE TITLE
Doesn't seem to work after opening Runelite; only works after disabling and enabling the plugin

### ISSUE THREAD

**Issue by Feldherren** [climbridecode/herblore-recipes#18]
The plugin doesn't seem to work right after you open RuneLite; items just display their normal mouseover text. The issue can be fixed temporarily by disabling and re-enabling the plugin, but this needs to be done again every time you open RuneLite.

RuneLite version 1.10.12.2

**Comment by climbridecode** [comment]
I've seen this happen intermittently. I've seen the plugin work upon first startup of RuneLite and other times it doesn't work. I think it's because the `itemManager` isn't always loaded properly when the Plugin tries to load? Idk, it's weird. It's due to a `NullPointerException` that gets thrown only sometimes, when an item id is passed to the `itemManager` to find an item. The thing is, the item IDs never change. And the way I'm building it never changes. So yeah, race condition is my hunch. 

Can change the plugin to load the tooltip cache at a different point, maybe when user logs in.

**Comment by climbridecode** [comment]
Hopefully when https://github.com/runelite/plugin-hub/pull/5299 is merged, this goes away. I'll keep an eye open too. I haven't been able to reproduce this with the changes in that commit.
